# Default worker is for dev only.
# See omaps and organicmaps environments below for production.
name = 'url-processor'
# Organic Maps CF Account ID.
account_id = '462f578f0939f041e2c24ec99adce458'
workers_dev = true
compatibility_date = '2022-11-21'
main = './workers-site/index.js'

[site]
bucket = './public'

[build]
command = 'npm i --prefer-offline --no-audit && npm run build'

[vars]
DEBUG = true

[env.omaps]
name = 'url-processor-omaps'
workers_dev = false
# See the full list of handled files in the code.
route = 'omaps.app/*'

[env.omaps.vars]
DEBUG = false
